import type { LeadStage, Role } from "./domain";

export const PORTAL_NAME = "GoAccelovate Global Partner Program";

export const LEAD_STAGES: LeadStage[] = [
  "Identified Opportunity",
  "Outreach Started",
  "In Communication",
  "Discovery Call",
  "On Hold",
  "Contract Sent",
  "Advance Pending",
  "Advance Confirmed",
  "Sent to Product",
  "Done by Product",
  "Client Review",
  "Under Revisions",
  "Final Payment Clearance",
  "Final Handoff",
  "Closed Won",
  "Closed Lost",
];

export const PARTNER_CONTROLLED_STAGES: LeadStage[] = [
  "Identified Opportunity",
  "Outreach Started",
  "In Communication",
  "Discovery Call",
];

export const ADMIN_CONTROLLED_STAGES: LeadStage[] = [
  "Contract Sent",
  "Advance Pending",
  "Advance Confirmed",
  "Sent to Product",
  "Done by Product",
  "Client Review",
  "Under Revisions",
  "Final Payment Clearance",
  "Final Handoff",
  "Closed Won",
];

export const ADVANCE_PAYMENT_STAGES: LeadStage[] = [
  "Advance Confirmed",
  "Sent to Product",
  "Done by Product",
  "Client Review",
  "Under Revisions",
  "Final Payment Clearance",
  "Final Handoff",
  "Closed Won",
];

export const FINAL_PAYMENT_STAGES: LeadStage[] = [
  "Final Payment Clearance",
  "Final Handoff",
  "Closed Won",
];

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const INDUSTRIES = [
  "Advertising and Marketing",
  "Agriculture",
  "Automotive",
  "Banking",
  "Biotechnology",
  "Construction",
  "Consulting",
  "Consumer Goods",
  "Education",
  "Energy and Utilities",
  "Entertainment and Media",
  "Financial Services",
  "FinTech",
  "Food and Beverage",
  "Government and Public Sector",
  "Healthcare",
  "HealthTech",
  "Hospitality and Travel",
  "Insurance",
  "Legal Services",
  "Logistics and Supply Chain",
  "Manufacturing",
  "Nonprofit",
  "Pharmaceuticals",
  "Professional Services",
  "Real Estate",
  "Retail and E-commerce",
  "SaaS",
  "Telecommunications",
  "Technology",
  "Transportation",
  "Other",
];

export function canMoveLeadStage(
  role: Role,
  currentStage: LeadStage,
  targetStage: LeadStage,
  previousStage?: LeadStage,
) {
  if (currentStage === "On Hold") {
    if (!previousStage || targetStage !== previousStage) return false;
    if (role === "admin" || role === "super_admin") return true;
    return role === "partner" && PARTNER_CONTROLLED_STAGES.includes(previousStage);
  }
  if (role === "admin" || role === "super_admin") return true;
  if (role !== "partner") return false;
  if (currentStage === "Closed Won" || currentStage === "Closed Lost") return false;
  if (targetStage === "Closed Lost" || targetStage === "On Hold") return true;
  if (ADMIN_CONTROLLED_STAGES.includes(currentStage)) return false;
  return PARTNER_CONTROLLED_STAGES.includes(targetStage);
}

export function allowedLeadStageTargets(
  role: Role,
  currentStage: LeadStage,
  previousStage?: LeadStage,
) {
  return LEAD_STAGES.filter(
    (targetStage) =>
      targetStage === currentStage ||
      canMoveLeadStage(role, currentStage, targetStage, previousStage),
  );
}

export function isCommercialStage(stage: LeadStage, previousStage?: LeadStage) {
  return (
    ADMIN_CONTROLLED_STAGES.includes(stage) ||
    stage === "Closed Won" ||
    (stage === "On Hold" &&
      Boolean(previousStage && ADMIN_CONTROLLED_STAGES.includes(previousStage)))
  );
}

export function canRecordClientPayment(paymentType: "Advance" | "Final", stage: LeadStage) {
  return (paymentType === "Advance" ? ADVANCE_PAYMENT_STAGES : FINAL_PAYMENT_STAGES).includes(
    stage,
  );
}
