/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api.users'
import { Route as ApiInvitationsRouteImport } from './routes/api.invitations'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSubmitLeadRouteImport } from './routes/_app.submit-lead'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPipelineListRouteImport } from './routes/_app.pipeline-list'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppPayoutsRouteImport } from './routes/_app.payouts'
import { Route as AppPartnersRouteImport } from './routes/_app.partners'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCommissionsRouteImport } from './routes/_app.commissions'
import { Route as AppClientPaymentsRouteImport } from './routes/_app.client-payments'
import { Route as AppAuditLogRouteImport } from './routes/_app.audit-log'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'
import { Route as AppPartnersIdRouteImport } from './routes/_app.partners.$id'
import { Route as AppLegalTypeRouteImport } from './routes/_app.legal.$type'
import { Route as AppLeadsIdRouteImport } from './routes/_app.leads.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitationsRoute = ApiInvitationsRouteImport.update({
  id: '/api/invitations',
  path: '/api/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmitLeadRoute = AppSubmitLeadRouteImport.update({
  id: '/submit-lead',
  path: '/submit-lead',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineListRoute = AppPipelineListRouteImport.update({
  id: '/pipeline-list',
  path: '/pipeline-list',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoutsRoute = AppPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppClientPaymentsRoute = AppClientPaymentsRouteImport.update({
  id: '/client-payments',
  path: '/client-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersIdRoute = AppPartnersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPartnersRoute,
} as any)
const AppLegalTypeRoute = AppLegalTypeRouteImport.update({
  id: '/legal/$type',
  path: '/legal/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIdRoute = AppLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/audit-log': typeof AppAuditLogRoute
  '/client-payments': typeof AppClientPaymentsRoute
  '/commissions': typeof AppCommissionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/onboarding': typeof AppOnboardingRoute
  '/partners': typeof AppPartnersRouteWithChildren
  '/payouts': typeof AppPayoutsRoute
  '/pipeline': typeof AppPipelineRoute
  '/pipeline-list': typeof AppPipelineListRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/submit-lead': typeof AppSubmitLeadRoute
  '/users': typeof AppUsersRoute
  '/api/invitations': typeof ApiInvitationsRoute
  '/api/users': typeof ApiUsersRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/legal/$type': typeof AppLegalTypeRoute
  '/partners/$id': typeof AppPartnersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/audit-log': typeof AppAuditLogRoute
  '/client-payments': typeof AppClientPaymentsRoute
  '/commissions': typeof AppCommissionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/onboarding': typeof AppOnboardingRoute
  '/partners': typeof AppPartnersRouteWithChildren
  '/payouts': typeof AppPayoutsRoute
  '/pipeline': typeof AppPipelineRoute
  '/pipeline-list': typeof AppPipelineListRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/submit-lead': typeof AppSubmitLeadRoute
  '/users': typeof AppUsersRoute
  '/api/invitations': typeof ApiInvitationsRoute
  '/api/users': typeof ApiUsersRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/legal/$type': typeof AppLegalTypeRoute
  '/partners/$id': typeof AppPartnersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/audit-log': typeof AppAuditLogRoute
  '/_app/client-payments': typeof AppClientPaymentsRoute
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/partners': typeof AppPartnersRouteWithChildren
  '/_app/payouts': typeof AppPayoutsRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/pipeline-list': typeof AppPipelineListRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/submit-lead': typeof AppSubmitLeadRoute
  '/_app/users': typeof AppUsersRoute
  '/api/invitations': typeof ApiInvitationsRoute
  '/api/users': typeof ApiUsersRoute
  '/_app/leads/$id': typeof AppLeadsIdRoute
  '/_app/legal/$type': typeof AppLegalTypeRoute
  '/_app/partners/$id': typeof AppPartnersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/invitation'
    | '/login'
    | '/announcements'
    | '/audit-log'
    | '/client-payments'
    | '/commissions'
    | '/dashboard'
    | '/leads'
    | '/onboarding'
    | '/partners'
    | '/payouts'
    | '/pipeline'
    | '/pipeline-list'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/submit-lead'
    | '/users'
    | '/api/invitations'
    | '/api/users'
    | '/leads/$id'
    | '/legal/$type'
    | '/partners/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/invitation'
    | '/login'
    | '/announcements'
    | '/audit-log'
    | '/client-payments'
    | '/commissions'
    | '/dashboard'
    | '/leads'
    | '/onboarding'
    | '/partners'
    | '/payouts'
    | '/pipeline'
    | '/pipeline-list'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/submit-lead'
    | '/users'
    | '/api/invitations'
    | '/api/users'
    | '/leads/$id'
    | '/legal/$type'
    | '/partners/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/access-denied'
    | '/forgot-password'
    | '/invitation'
    | '/login'
    | '/_app/announcements'
    | '/_app/audit-log'
    | '/_app/client-payments'
    | '/_app/commissions'
    | '/_app/dashboard'
    | '/_app/leads'
    | '/_app/onboarding'
    | '/_app/partners'
    | '/_app/payouts'
    | '/_app/pipeline'
    | '/_app/pipeline-list'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/submit-lead'
    | '/_app/users'
    | '/api/invitations'
    | '/api/users'
    | '/_app/leads/$id'
    | '/_app/legal/$type'
    | '/_app/partners/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvitationRoute: typeof InvitationRoute
  LoginRoute: typeof LoginRoute
  ApiInvitationsRoute: typeof ApiInvitationsRoute
  ApiUsersRoute: typeof ApiUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invitations': {
      id: '/api/invitations'
      path: '/api/invitations'
      fullPath: '/api/invitations'
      preLoaderRoute: typeof ApiInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submit-lead': {
      id: '/_app/submit-lead'
      path: '/submit-lead'
      fullPath: '/submit-lead'
      preLoaderRoute: typeof AppSubmitLeadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline-list': {
      id: '/_app/pipeline-list'
      path: '/pipeline-list'
      fullPath: '/pipeline-list'
      preLoaderRoute: typeof AppPipelineListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payouts': {
      id: '/_app/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AppPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners': {
      id: '/_app/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client-payments': {
      id: '/_app/client-payments'
      path: '/client-payments'
      fullPath: '/client-payments'
      preLoaderRoute: typeof AppClientPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-log': {
      id: '/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners/$id': {
      id: '/_app/partners/$id'
      path: '/$id'
      fullPath: '/partners/$id'
      preLoaderRoute: typeof AppPartnersIdRouteImport
      parentRoute: typeof AppPartnersRoute
    }
    '/_app/legal/$type': {
      id: '/_app/legal/$type'
      path: '/legal/$type'
      fullPath: '/legal/$type'
      preLoaderRoute: typeof AppLegalTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$id': {
      id: '/_app/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AppLeadsIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
  }
}

interface AppLeadsRouteChildren {
  AppLeadsIdRoute: typeof AppLeadsIdRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsIdRoute: AppLeadsIdRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppPartnersRouteChildren {
  AppPartnersIdRoute: typeof AppPartnersIdRoute
}

const AppPartnersRouteChildren: AppPartnersRouteChildren = {
  AppPartnersIdRoute: AppPartnersIdRoute,
}

const AppPartnersRouteWithChildren = AppPartnersRoute._addFileChildren(
  AppPartnersRouteChildren,
)

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppClientPaymentsRoute: typeof AppClientPaymentsRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPartnersRoute: typeof AppPartnersRouteWithChildren
  AppPayoutsRoute: typeof AppPayoutsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPipelineListRoute: typeof AppPipelineListRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubmitLeadRoute: typeof AppSubmitLeadRoute
  AppUsersRoute: typeof AppUsersRoute
  AppLegalTypeRoute: typeof AppLegalTypeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAuditLogRoute: AppAuditLogRoute,
  AppClientPaymentsRoute: AppClientPaymentsRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPartnersRoute: AppPartnersRouteWithChildren,
  AppPayoutsRoute: AppPayoutsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPipelineListRoute: AppPipelineListRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubmitLeadRoute: AppSubmitLeadRoute,
  AppUsersRoute: AppUsersRoute,
  AppLegalTypeRoute: AppLegalTypeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvitationRoute: InvitationRoute,
  LoginRoute: LoginRoute,
  ApiInvitationsRoute: ApiInvitationsRoute,
  ApiUsersRoute: ApiUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
